import React from 'react';
import Pizza from "./Pizza.jsx";
import {connect} from "react-redux";
import {followThunk, followValye, pushKolVo, pushKorzina,
    setImgThunk, setMinZakaz, setZakaz,unfollowThunk} from "../reducers/PizzaReducer";


class PizzaContainer extends React.Component {

    img = [
        {  img: "https://images.dominos.by/media/dominos/osg/api/2021/10/14/izi_frizi_small.png",
            name: "Изи Фризи",
            ingr: "Сыр моцарелла, Картофель фри, Соус Чесночный, Сосиски куриные, Ветчина",
            cost: 25.99,
            masa: "640 гр.",
            svg:"http://www.w3.org/2000/svg",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:1,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2021/10/14/chedderoni_small.png",
            name: "Чеддерони",
            ingr: "Крем фреш, Чеддер, Ветчина, Пепперони, Сыр моцарелла",
            cost: 25.99,
            masa: "640 гр.",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:2,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2021/08/05/Beef_BBQ_small-min.png",
            name: "Биф BBQ",
            ingr: "Телятина, Шпинат, Сыр моцарелла, Черри, Соус барбекю, Баварские колбаски",
            cost: 25.99,
            masa: "640 гр.",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:3,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2020/03/11/govyadina_burger_small.png",
            name: "Говядина BURGER",
            ingr: "Шампиньоны, Телятина, Сыр моцарелла, Соус Бургер, Лук, Огурцы",
            cost: 25.99,
            asa: "640 гр.",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:4,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2021/08/05/kolbaski_i_opyata_small-min.png",
            name: "Колбаски и опята",
            ingr: "Баварские колбаски, Опята, Сыр моцарелла, Соус Чесночный, Горчица",
            cost: 25.99,
            masa: "640 гр.",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:5,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2020/11/18/chiken_fresh_small.png",
            name: "Чикен Ранч",
            ingr: "Соус Чесночный, Томаты, Сыр моцарелла, Курица",
            cost: 25.99,
            masa: "640 гр.",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:6,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2018/09/12/carbonara.png",
            name: "Карбонара",
            ingr: "Шампиньоны, Лук, Крем фреш, Бекон, Сыр моцарелла, Ветчина",
            cost: 25.99,
            masa: "640 гр.",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:7,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2018/09/12/firmennaya.png",
            name: "Доминос Фирменная",
            ingr: "Пармезан, Курица, Сыр моцарелла, Лук, Томатный соус Domino's, Бекон, Сладкий перец, Томаты, Буженина, Телятина, Шампиньоны",
            cost: 25.99,
            masa: "640 гр.",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:8,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2021/06/10/meksikanskaya_small.png",
            name: "Мексиканская",
            ingr: "Сыр моцарелла, Сладкий перец, Соус Бургер, Халапеньо, Курица, Кукуруза, Томаты",
            cost: 25.99,
            masa: "945 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:9,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2018/09/12/provence.png",
            name: "Прованс",
            ingr: "Томаты, Голубой сыр, Сыр моцарелла, Крем фреш, Пепперони, Ветчина",
            cost: 27.89,
            masa: "545 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:10,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2019/07/03/myunkhenskaya_small.png",
            name: "Мюнхенская",
            ingr: "Баварские колбаски, Томаты, Соус барбекю, Горчица, Сыр моцарелла, Мюнхенские колбаски, Ветчина",
            cost: 33.39,
            masa: "590 гр",dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:11,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2018/09/12/5_syrov.png",
            name: "5 Сыров",
            ingr: "Фета, Крем фреш, Голубой сыр, Пармезан, Чеддер, Сыр моцарелла",
            cost: 25.99,
            masa: "640 гр.",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:12,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2021/03/23/rivyera_small_mNcDSaS.png",
            name: "Ривьера",
            ingr: "Соус Чесночный, Шпинат, Сыр моцарелла, Черри, Ветчина, Маслины",
            cost: 26.49,
            masa: "650 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:13,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2019/10/18/fermerskaya_small.png",
            name: "Фермерская",
            ingr: "Огурцы, Ветчина, Сыр моцарелла, Соус Чесночный",
            cost: 26.39,
            masa: "585 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:14,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2019/07/29/gribnaya_small.png",
            name: "Грибная с голубым сыром",
            ingr: "Голубой сыр, Сыр моцарелла, Опята, Соус Чесночный, Шампиньоны",
            cost: 31.39,
            masa: "835 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:15,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2018/09/12/spice.png",
            name: "Спайси",
            ingr: "Пепперони, Халапеньо, Сыр моцарелла, Томатный соус Domino's, Бекон, Томаты",
            cost: 26.49,
            masa: "880 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:16,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2020/04/21/tsyplenok__dominator_small-min.png",
            name: "Цыпленок Доминатор",
            ingr: "оматы, Мюнхенские колбаски, Курица, Сыр моцарелла, Соус Чесночный, Огурцы, Сладкий перец",
            cost: 28.89,
            masa: "635 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:17,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2020/04/21/eksravaganzza_small-min.png",
            name: "ЭкстраваганZZа",
            ingr: "Телятина, Шампиньоны, Томатный соус Domino's, Сыр моцарелла, Пепперони, Лук, Сладкий перец, Оливки, Ветчина",
            cost: 28.49,
            masa: "480 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:18,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2020/07/14/super_pepperoni_small-min.png",
            name: "Супер Пепперони",
            ingr: "Томатный соус Domino's, Сыр моцарелла, Пепперони",
            cost: 26.49,
            masa: "940 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:19,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2018/09/12/barbecue.png",
            name: "Барбекю",
            ingr: "Лук, Курица, Соус барбекю, Бекон, Шампиньоны, Сыр моцарелла",
            cost: 27.89,
            masa: "570 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:20,
            followed:false,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2018/09/12/kantri.png",
            name: "Кантри",
            ingr: "Соус Чесночный, Лук, Ветчина, Сыр моцарелла, Огурцы, Шампиньоны, Бекон",
            cost: 32.39,
            masa: "630 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:21,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2020/01/09/gipnotika_small.png",
            name: "Гипнотика",
            ingr: "Телятина, Бекон, Крем фреш, Пепперони, Обжаренный лук, Шпинат, Соус барбекю, Сыр моцарелла",
            cost: 26.49,
            masa: "630 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:22,
            followed:true,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2018/09/12/pepperoni_bluz.png",
            name: "Пепперони Блюз",
            ingr: "Голубой сыр, Пепперони, Сыр моцарелла, Соус Чесночный",
            cost: 20.49,
            masa: "345 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:23,
            followed:false,
            valye:false,
            zakaz:1
        },
        {
            img: "https://images.dominos.by/media/dominos/osg/api/2018/09/12/toskana.png",
            name: "Тоскана",
            ingr: "Томаты, Фета, Курица, Сыр моцарелла, Соус Чесночный, Шпинат",
            cost: 26.49,
            masa: "625 гр",
            dopimg1:"https://dominos.by/static/images/img-d19422.png",
            dopimg2:"https://images.dominos.by/media/dominos/topping/small/2021/05/20/mozarella-mini-170x127.png",
            dop1:"Хот-Дог борт",
            dop2:"Моцарелла-mini",
            dopprice1:"5.90 руб.",
            dopprice2:"2.49 руб.",
            id:24,
            followed:true,
            valye:false,
            zakaz:1
        }
    ];


    componentDidMount() {
        this.props.setImgThunk(this.img)

    };



    render() {
        return (
            <div>
                <Pizza {...this.props} pizza={this.props.pizza} pushKorzina={this.props.pushKorzina}
                       kol_vo={this.props.kol_vo} pushKolVo={this.props.pushKolVo}
                       follow={this.props.followThunk} unfollow={this.props.unfollowThunk}
                       followValye={this.props.followValye}  setZakaz={this.props.setZakaz} setMinZakaz={this.props.setMinZakaz}
                       isAuth={this.props.isAuth}/>
            </div>
        )
    }
}

let mapStateToProps = (state) => {

    return {
        pizza: state.pizza,
        korzina:state.pizza.korzina,
        kol_vo:state.pizza.kol_vo,
        isAuth: state.login.isAuth

    }
};
export default connect(mapStateToProps, {setImgThunk,followThunk,unfollowThunk,pushKolVo,pushKorzina,followValye,setZakaz,setMinZakaz})(PizzaContainer);